// @flow
export const RESET_STATE = '@@COMPONENT_RESET_STATE'
export const PROCESS_BATCH = '@@COMPONENT_PROCESS_BATCH'
export const MOUNT_PATH = '@@MOUNT_PATH'
export const UUID = '@@UUID'
export const BATCH = '@@BATCH'
export const NEW_STATE = '@@NEW_STATE'
export const ACTIONS = '@@ACTIONS'
export const PROP_MOUNT_PATH = 'reduxMountPath'
export const PROP_PERSIST = 'reduxPersist'
